apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: babelfish-tls
  annotations:
    cert-manager.io/issuer: "letsencrypt-prod"
spec:
  secretName: babelfish-tls
  issuerRef:
    group: cert-manager.io
    name: letsencrypt-prod
    kind: Issuer
  dnsNames:
  - 'babelfish.data-container.net'