FROM oydeu/dc-base:arm64v8
MAINTAINER "Christoph Fabianek" christoph@ownyourdata.eu

RUN apt-get update && \
	apt-get install -y \
		cron \
		curl \
		redis-tools && \
	rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

COPY Gemfile.extend $WORKDIR
RUN bundle install && bundle update
COPY . .

# CMD ["./script/redis.sh"]
CMD ["rake", "redis_listener:start"]

# EXPOSE 3000
