FROM oydeu/dc-base:arm64v8
MAINTAINER "Christoph Fabianek" christoph@ownyourdata.eu

RUN apt-get update && \
	apt-get install -y --no-install-recommends \
		curl \
		npm && \
	curl -fsSL https://deb.nodesource.com/setup_18.x | bash - && \
	apt -y install nodejs && \
	rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
RUN npm init -y && npm i web3@1.10.0

COPY Gemfile.extend .
RUN bundle install && bundle update
COPY . .

CMD ["./script/init.sh"]

EXPOSE 3000
