apiVersion: apps/v1
kind: Deployment
metadata:
  name: regapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: regapi
  template:
    metadata:
      name: regapi
      labels:
        app: regapi
    spec:
      containers:
      - name: regapi
        image: oydeu/dc-regapi:latest
        ports:
        - containerPort: 3000
        env:
          - name: LANG
            value: C.UTF-8
          - name: RAILS_LOG_TO_STDOUT
            value: "TRUE"
          - name: RAILS_SERVE_STATIC_FILES
            value: "TRUE"
          - name: RAILS_ENV
            value: production
          - name: AUTH
            value: "TRUE"
          - name: REDIS_HOST
            value: redis-0.redis.redis.svc.cluster.local
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: general-secrets
                key: redis-passwd
          - name: DC_DB
            value: kubernetes
          - name: DB2_HOST
            value: postgres
          - name: DB2_NAME
            value: regapi
          - name: DB2_USER
            value: postgres
          - name: POSTGRES2_PASSWORD
            valueFrom:
              secretKeyRef:
                name: general-secrets
                key: db2-passwd
          - name: RAILS_CONFIG_HOSTS
            value: "regapi.staging.dec112.eu"
          - name: DEFAULT_DID_OAUTH_APP
            value: oydid
          - name: DEFAULT_VC_OAUTH_APP
            value: oydid-vc
---
kind: Service
apiVersion: v1
metadata:
  name: regapi
spec:
  selector:
    app: regapi
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: regapi
  annotations:
    kubernetes.io/ingress.class: "nginx"
    certmanager.io/issuer: "letsencrypt-prod"
spec: 
  tls:
  - hosts:
    - regapi.staging.dec112.eu
    # - regapi.data-container.net
    secretName: regapi-tls
  rules:
  - host: regapi.staging.dec112.eu
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: regapi
            port:
              number: 80
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: regapi-tls
  annotations:
    cert-manager.io/issuer: "letsencrypt-prod"
spec:
  secretName: regapi-tls
  issuerRef:
    group: cert-manager.io
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - 'regapi.staging.dec112.eu'
