# Event types for CollectionEvent
CE_CREATE_COLLECTION = 1
CE_UPDATE_COLLECTION = 2
CE_DELETE_COLLECTION = 3
CE_ACCESS_COLLECTION = 4

CE_CREATE_OBJECT = 11
CE_UPDATE_OBJECT = 12
CE_DELETE_OBJECT = 13
CE_READ_OBJECT   = 14

CE_WRITE_PAYLOAD = 21
CE_READ_PAYLOAD  = 22